# Generated by Django 5.1.7 on 2025-08-13 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Proyecto')),
                ('codigo', models.CharField(help_text='Código único para identificar el proyecto (ej: PROJ001)', max_length=20, unique=True, verbose_name='Código del Proyecto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cliente', models.CharField(blank=True, max_length=100, verbose_name='Cliente')),
                ('base_datos_principal', models.CharField(blank=True, max_length=100, verbose_name='Base de Datos Principal')),
                ('motor_bd', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('sqlserver', 'SQL Server'), ('oracle', 'Oracle'), ('sqlite', 'SQLite')], default='mysql', max_length=50, verbose_name='Motor de Base de Datos')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_pausa', 'En Pausa'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin Estimada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('configuraciones', models.JSONField(blank=True, default=dict, help_text='Configuraciones específicas del proyecto en formato JSON', verbose_name='Configuraciones Adicionales')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('lider_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_liderados', to=settings.AUTH_USER_MODEL, verbose_name='Líder del Proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('crear_tabla', 'Creación de tablas base de datos'), ('modificar_tabla', 'Modificación de tabla base de datos'), ('compilar_objetos', 'Compilación de objetos'), ('asignar_permisos', 'Asignación de permisos'), ('crear_usuarios', 'Creación de usuarios y roles'), ('pull_request', 'Solicitud pull request'), ('despliegue', 'Solicitud de despliegue'), ('crear_bd', 'Creación de bases de datos'), ('crear_esquemas', 'Creación de esquemas'), ('compilar_scripts_qa', 'Compilación de scripts de tickets en QA'), ('compilar_scripts_pu', 'Compilación de scripts de tickets en PU')], max_length=30)),
                ('tipo_archivo', models.CharField(blank=True, choices=[('excel', 'Excel'), ('zip', 'ZIP'), ('sql', 'SQL')], max_length=10, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='solicitudes/')),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('pendiente_aprobacion_lider', 'Pendiente aprobación líder')], default='registrada', max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('base_datos_aplicacion', models.CharField(help_text='Base de datos o aplicación donde se aplicará', max_length=100)),
                ('correo_notificacion', models.EmailField(help_text='Correo para notificaciones', max_length=254)),
                ('ambientes_ejecucion', models.JSONField(blank=True, default=list, help_text='Ambientes donde ejecutar (para scripts)')),
                ('url_commit', models.URLField(blank=True, null=True)),
                ('nombre_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('entorno', models.CharField(blank=True, max_length=50, null=True)),
                ('script_sql_generado', models.TextField(blank=True, null=True)),
                ('estructura_validada', models.BooleanField(default=False, help_text='Si la estructura del archivo fue validada')),
                ('usuario_creado', models.CharField(blank=True, max_length=100, null=True)),
                ('password_generado', models.CharField(blank=True, max_length=100, null=True)),
                ('lider_proyecto', models.ForeignKey(blank=True, help_text='Líder que debe aprobar (para creación de usuarios)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_lideradas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='tickets.proyecto', verbose_name='Proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('registrada', 'Registrada'), ('revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('pendiente_aprobacion_lider', 'Pendiente aprobación líder')], max_length=30)),
                ('estado_nuevo', models.CharField(choices=[('registrada', 'Registrada'), ('revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('pendiente_aprobacion_lider', 'Pendiente aprobación líder')], max_length=30)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('usuario_cambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tickets.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.solicitud')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('dev', 'Ingeniero de Desarrollo'), ('db', 'Ingeniero de Bases de Datos'), ('devops', 'Ingeniero DevOps'), ('admin', 'Administrador'), ('lider', 'Líder de Proyecto')], default='dev', max_length=10)),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proyectos_asignados', models.ManyToManyField(blank=True, related_name='miembros_equipo', to='tickets.proyecto', verbose_name='Proyectos Asignados')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionEstructuraExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(max_length=50)),
                ('estructura_json', models.TextField(help_text='JSON con la estructura esperada')),
                ('descripcion', models.TextField(blank=True)),
                ('nombre', models.CharField(default='Default', max_length=100, verbose_name='Nombre de la Configuración')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_excel', to='tickets.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Configuración de Estructura Excel',
                'verbose_name_plural': 'Configuraciones de Estructura Excel',
                'unique_together': {('proyecto', 'tipo_solicitud', 'nombre')},
            },
        ),
    ]
