# Generated by Django 5.1.7 on 2025-08-06 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('crear_tabla', 'Creación de tablas base de datos'), ('modificar_tabla', 'Modificación de tabla base de datos'), ('compilar_objetos', 'Compilación de objetos'), ('asignar_permisos', 'Asignación de permisos'), ('crear_usuarios', 'Creación de usuarios y roles'), ('pull_request', 'Solicitud pull request'), ('despliegue', 'Solicitud de despliegue')], max_length=20)),
                ('tipo_archivo', models.CharField(blank=True, choices=[('excel', 'Excel'), ('zip', 'ZIP'), ('sql', 'SQL')], max_length=10, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='solicitudes/')),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada')], default='registrada', max_length=15)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('url_commit', models.URLField(blank=True, null=True)),
                ('nombre_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('entorno', models.CharField(blank=True, max_length=50, null=True)),
                ('script_sql_generado', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('registrada', 'Registrada'), ('revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada')], max_length=15)),
                ('estado_nuevo', models.CharField(choices=[('registrada', 'Registrada'), ('revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada')], max_length=15)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('usuario_cambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tickets.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.solicitud')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('dev', 'Ingeniero de Desarrollo'), ('db', 'Ingeniero de Bases de Datos'), ('devops', 'Ingeniero DevOps'), ('admin', 'Administrador')], default='dev', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
