# Generated by Django 5.1.7 on 2025-08-06 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEstructuraExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(max_length=50, unique=True)),
                ('estructura_json', models.TextField(help_text='JSON con la estructura esperada')),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='ambientes_ejecucion',
            field=models.JSONField(blank=True, default=list, help_text='Ambientes donde ejecutar (para scripts)'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='base_datos_aplicacion',
            field=models.CharField(default=2, help_text='Base de datos o aplicación donde se aplicará', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='correo_notificacion',
            field=models.EmailField(default=1, help_text='Correo para notificaciones', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estructura_validada',
            field=models.BooleanField(default=False, help_text='Si la estructura del archivo fue validada'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='lider_proyecto',
            field=models.ForeignKey(blank=True, help_text='Líder que debe aprobar (para creación de usuarios)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_lideradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='password_generado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario_creado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.CharField(choices=[('registrada', 'Registrada'), ('revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('pendiente_aprobacion_lider', 'Pendiente aprobación líder')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('registrada', 'Registrada'), ('revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('pendiente_aprobacion_lider', 'Pendiente aprobación líder')], max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('registrada', 'Registrada'), ('revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('pendiente_aprobacion_lider', 'Pendiente aprobación líder')], default='registrada', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_solicitud',
            field=models.CharField(choices=[('crear_tabla', 'Creación de tablas base de datos'), ('modificar_tabla', 'Modificación de tabla base de datos'), ('compilar_objetos', 'Compilación de objetos'), ('asignar_permisos', 'Asignación de permisos'), ('crear_usuarios', 'Creación de usuarios y roles'), ('pull_request', 'Solicitud pull request'), ('despliegue', 'Solicitud de despliegue'), ('crear_bd', 'Creación de bases de datos'), ('crear_esquemas', 'Creación de esquemas'), ('compilar_scripts_qa', 'Compilación de scripts de tickets en QA'), ('compilar_scripts_pu', 'Compilación de scripts de tickets en PU')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('dev', 'Ingeniero de Desarrollo'), ('db', 'Ingeniero de Bases de Datos'), ('devops', 'Ingeniero DevOps'), ('admin', 'Administrador'), ('lider', 'Líder de Proyecto')], default='dev', max_length=10),
        ),
    ]
